---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 1
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          *app :
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.5.19@sha256:6bcdb458af47c555f2b0e6f39275ba128d3c48197c118f6fd58fec2db612bc74
            env:
              ENABLE_LOGIN_FORM: false
              DEFAULT_USER_ROLE: user
              OLLAMA_BASE_URL: http://ollama.cluster-utilities.svc.cluster.local:11434
              ENABLE_AUTOCOMPLETE_GENERATION: false # annoying
              WEBUI_URL: &host https://ai.${SECRET_DOMAIN}
              CORS_ALLOW_ORIGIN: *host
              SEARXNG_QUERY_URL: http://searxng.home.svc.cluster.local:8080/search?q=<query>

              ENABLE_RAG_WEB_SEARCH: true
              RAG_WEB_SEARCH_ENGINE: searxng
              VECTOR_DB: pgvector
              RAG_EMBEDDING_ENGINE: ollama

              ENABLE_OAUTH_SIGNUP: true
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
              OAUTH_PROVIDER_NAME: Authentik
            envFrom:
              - secretRef:
                  name: open-webui-secret
            securityContext:
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 800m
                memory: 100Mi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      *app :
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      *app :
        className: external
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "1g"
        hosts:
          - host: ai.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/backend/data
      tmp:
        type: emptyDir
