---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          *app :
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.8@sha256:89b3eed928517acb2d7cd40dc574f1e73108d4b0222a8ee99a9fdc4044c7a2c2
            env:
              ENABLE_LOGIN_FORM: false
              DEFAULT_USER_ROLE: user
              ENABLE_AUTOCOMPLETE_GENERATION: false # annoying
              WEBUI_URL: &host https://ai.${SECRET_DOMAIN}
              CORS_ALLOW_ORIGIN: *host
              SEARXNG_QUERY_URL: http://searxng.home.svc.cluster.local:8080/search?q=<query>

              ENABLE_OLLAMA_API: false
              OPENAI_API_BASE_URLS: "http://mlc-llm-mistral.home.svc.cluster.local:8080/v1;http://mlc-llm-r1-phi.home.svc.cluster.local:8080/v1;http://mlc-llm-qwen.home.svc.cluster.local:8080/v1"

              ENABLE_RAG_WEB_SEARCH: true
              RAG_WEB_SEARCH_ENGINE: searxng
              VECTOR_DB: pgvector
              RAG_EMBEDDING_ENGINE: ollama

              ENABLE_OAUTH_SIGNUP: true
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
              OAUTH_PROVIDER_NAME: Pocket ID

              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: ${APP}-db-app
                    key: uri
            envFrom:
              - secretRef:
                  name: open-webui-secret
            securityContext:
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 800m
                memory: 100Mi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: Always
        seccompProfile: { type: RuntimeDefault }
    service:
      *app :
        controller: main
        ports:
          http:
            port: &port 8080
    route:
      *app :
        hostnames:
          - ai.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/backend/data
      tmp:
        type: emptyDir
