---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-gravity
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: flux-system
  install:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  values:
    tolerations:
      - key: "location"
        operator: "Equal"
        value: "cloud"
        effect: "NoSchedule"
      - key: "location"
        operator: "Equal"
        value: "house"
        effect: "NoSchedule"
    image:
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.18.0
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/beryju/gravity-external-dns
          tag: 906a956337f4f318bc6dc0ad74e02a02f81a780f
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
        env:
          - name: GRAVITY_URL
            value: http://gravity-http:8008/
          - name: GRAVITY_TOKEN
            valueFrom:
              secretKeyRef:
                name: ${APP}-secret
                key: TOKEN
    policy: sync
    triggerLoopOnEvent: true
    sources: ["crd", "gateway-httproute", "service"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
