---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &db d3savant-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'
spec:
  instances: 1
  affinity:
    nodeSelector:
      kubernetes.io/hostname: bonds
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5@sha256:078a06285f2e9ce54afadbb86c75584a8aca46a10255d17131b9b4d1f96a0ec2
  primaryUpdateStrategy: unsupervised
  postgresql:
    pg_hba:
      - host all all 172.16.0.0/16 md5
      - host all all 192.168.1.0/24 md5
  storage:
    size: 500Gi
    storageClass: zfs-nvme
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true

  backup:
    retentionPolicy: 7d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://backups/cnpg
      endpointURL: http://minio.cluster-utilities.svc.cluster.local:9000
      serverName: *db
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: minio-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: minio-secret-access-key
  # bootstrap:
  #   recovery:
  #     source: *db
  # externalClusters:
  #   - name: *db
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *db
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: d3savant
spec:
  schedule: "0 0 4 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: d3savant-db
